import io
import re
import json
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak, KeepTogether
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from reportlab.pdfgen import canvas

class NumberedCanvas(canvas.Canvas):
    """
    Canvas to calculate total page count and add headers/footers dynamically.
    """
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_decorations(num_pages)
            super().showPage()
        super().save()

    def draw_page_decorations(self, page_count):
        # Prevent headers/footers on first page (Cover page)
        if self._pageNumber == 1:
            return
            
        self.saveState()
        self.setFont("Helvetica", 9)
        self.setFillColor(colors.HexColor("#94a3b8")) # Gray text
        
        # Header text
        self.drawString(54, 750, "AI Research Assistant Agent - Research Report")
        self.setStrokeColor(colors.HexColor("#334155")) # Dark line
        self.setLineWidth(0.5)
        self.line(54, 742, 558, 742)
        
        # Footer text
        page_text = f"Page {self._pageNumber} of {page_count}"
        self.drawRightString(558, 40, page_text)
        self.drawString(54, 40, "Confidential - Generated by AI Research Agent")
        self.line(54, 52, 558, 52)
        
        self.restoreState()

def clean_html_for_pdf(html_text):
    if not html_text:
        return ""
    # Standardize spacing/newlines
    text = html_text.replace("\n", " ").strip()
    
    # Replace list tags
    text = re.sub(r'</?ul>', '', text)
    text = text.replace('<li>', '• ').replace('</li>', '<br/>')
    
    # Replace headers
    text = re.sub(r'<h3>', '<font size="13" color="#8b5cf6"><b>', text)
    text = re.sub(r'</h3>', '</b></font><br/>', text)
    text = re.sub(r'<h4>', '<font size="11" color="#a78bfa"><b>', text)
    text = re.sub(r'</h4>', '</b></font><br/>', text)
    
    # Replace paragraphs
    text = text.replace('<p>', '').replace('</p>', '<br/><br/>')
    
    # Replace divs and spans
    text = re.sub(r'<div[^>]*>', '', text)
    text = text.replace('</div>', '<br/>')
    
    # Replace question/answer classes
    text = text.replace('<div class="question">', '<b>Q: ').replace('<div class="answer">', '<b>A: ')
    
    # Strip any other tags except b, i, u, strong, em, font, br
    allowed_tags = ['b', 'i', 'u', 'strong', 'em', 'font', 'br']
    text = re.sub(r'<(?!/?(' + '|'.join(allowed_tags) + r')\b)[^>]*>', '', text)
    
    # Clean duplicate br's
    text = re.sub(r'(<br/>\s*){3,}', '<br/><br/>', text)
    return text.strip()

def generate_report_pdf(topic, report_data):
    """
    Creates a styled PDF document of the research report.
    Returns bytes of the PDF.
    """
    buffer = io.BytesIO()
    
    # 0.75-inch margins (54 points)
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        leftMargin=54,
        rightMargin=54,
        topMargin=72,
        bottomMargin=72
    )

    styles = getSampleStyleSheet()
    
    # Setup custom styles to match dark-theme/high-fidelity aesthetic
    primary_color = colors.HexColor("#0f172a") # Slate 900
    accent_color = colors.HexColor("#6366f1") # Indigo 500
    text_color = colors.HexColor("#1e293b") # Slate 800
    
    styles.add(ParagraphStyle(
        name='CoverTitle',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=28,
        leading=34,
        textColor=colors.HexColor("#1e1b4b"), # Dark indigo
        alignment=0,
        spaceAfter=15
    ))

    styles.add(ParagraphStyle(
        name='CoverSubtitle',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=14,
        leading=18,
        textColor=colors.HexColor("#4f46e5"),
        spaceAfter=30
    ))
    
    styles.add(ParagraphStyle(
        name='ReportHeading',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=16,
        leading=20,
        textColor=accent_color,
        spaceBefore=18,
        spaceAfter=8,
        keepWithNext=True
    ))

    styles.add(ParagraphStyle(
        name='ReportBody',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=10.5,
        leading=15,
        textColor=text_color,
        spaceAfter=8
    ))

    story = []
    
    # --- COVER PAGE ---
    story.append(Spacer(1, 100))
    story.append(Paragraph(f"AI RESEARCH REPORT", styles['CoverSubtitle']))
    story.append(Paragraph(topic.upper(), styles['CoverTitle']))
    
    # Decorative line
    story.append(Spacer(1, 10))
    # Line represented as empty Paragraph with underline or background
    story.append(Paragraph("<b>Generated by AI Research Assistant Agent</b>", styles['ReportBody']))
    
    import datetime
    date_str = datetime.datetime.now().strftime("%B %d, %Y at %I:%M %p")
    story.append(Paragraph(f"Date generated: {date_str}", styles['ReportBody']))
    
    story.append(Spacer(1, 40))
    story.append(Paragraph("This comprehensive document compiles multi-step Agentic AI research findings on the requested topic, covering in-depth concepts, summary takeaways, interview prep guides, practice quizzes, and an actionable learning roadmap.", styles['ReportBody']))
    story.append(PageBreak())
    
    # --- SECTION 1: EXPLANATION ---
    story.append(Paragraph("1. Understanding & Detailed Explanation", styles['ReportHeading']))
    explanation_clean = clean_html_for_pdf(report_data.get('explanation', ''))
    story.append(Paragraph(explanation_clean, styles['ReportBody']))
    story.append(Spacer(1, 15))

    # --- SECTION 2: KEY POINTS ---
    story.append(Paragraph("2. Key Takeaways", styles['ReportHeading']))
    key_points_clean = clean_html_for_pdf(report_data.get('key_points', ''))
    story.append(Paragraph(key_points_clean, styles['ReportBody']))
    story.append(Spacer(1, 15))

    # --- SECTION 3: ROADMAP ---
    story.append(Paragraph("3. Learning Roadmap", styles['ReportHeading']))
    roadmap_clean = clean_html_for_pdf(report_data.get('roadmap', ''))
    story.append(Paragraph(roadmap_clean, styles['ReportBody']))
    story.append(Spacer(1, 15))

    # --- SECTION 4: INTERVIEW PREP ---
    story.append(Paragraph("4. Interview Prep Q&A", styles['ReportHeading']))
    interview_clean = clean_html_for_pdf(report_data.get('interview_questions', ''))
    story.append(Paragraph(interview_clean, styles['ReportBody']))
    story.append(Spacer(1, 15))

    # --- SECTION 5: PRACTICE QUIZ ---
    story.append(Paragraph("5. Practice Quiz", styles['ReportHeading']))
    raw_quiz = report_data.get('quiz', '[]')
    try:
        quiz_list = json.loads(raw_quiz)
        quiz_html = ""
        for idx, item in enumerate(quiz_list):
            q_text = f"<b>Q{idx+1}: {item.get('question')}</b><br/>"
            options_text = ""
            for o in item.get('options', []):
                options_text += f"• {o}<br/>"
            ans_text = f"<i>Correct Answer: {item.get('answer')}</i><br/>"
            exp_text = f"Explanation: {item.get('explanation')}<br/><br/>"
            quiz_html += q_text + options_text + ans_text + exp_text
        story.append(Paragraph(clean_html_for_pdf(quiz_html), styles['ReportBody']))
    except Exception:
        # If parsing fails, fall back to writing raw quiz data
        story.append(Paragraph(clean_html_for_pdf(raw_quiz), styles['ReportBody']))
    story.append(Spacer(1, 15))

    # --- SECTION 6: SUMMARY ---
    story.append(Paragraph("6. Executive Summary", styles['ReportHeading']))
    summary_clean = clean_html_for_pdf(report_data.get('summary', ''))
    story.append(Paragraph(summary_clean, styles['ReportBody']))
    story.append(Spacer(1, 15))

    # --- SECTION 7: REFERENCES ---
    story.append(Paragraph("7. Useful References", styles['ReportHeading']))
    refs_clean = clean_html_for_pdf(report_data.get('references_data', ''))
    story.append(Paragraph(refs_clean, styles['ReportBody']))

    # Build the document
    doc.build(story, canvasmaker=NumberedCanvas)
    
    pdf_bytes = buffer.getvalue()
    buffer.close()
    return pdf_bytes
